#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [ `xrandr | grep HDMI | grep -c ' connected '` -eq 1 ]; then
#if [ `xrandr -q | grep -c 'HDMI-0 connected'` -eq 1 ]; then
#if [ `xrandr -q | grep -c '^HDMI.*connected'` -eq 1 ]; then
    bspc monitor LVDS-0 -d I II III IV V &
    bspc monitor HDMI-0 -d VI VII VIII IX X &
else
    bspc monitor LVDS-0 -d I II III IV V VI VII VIII IX X &
fi
#startup

bspc config border_width         2
bspc config window_gap          12

#bspc config top_padding         30
#bspc config left_padding        0
#bspc config right_padding       0
#bspc config bottom_padding      0


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/rhuamani/Escritorio/rhuamani/images/fondo_night.jpg
~/.config/polybar/./launch.sh
wmname LG3D
bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 0
xsetroot -cursor_name left_ptr &
